[build-system]
requires = ["setuptools>=77", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "emcee"
description = "The Python ensemble sampling toolkit for MCMC"
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Daniel Foreman-Mackey", email = "foreman.mackey@gmail.com" },
]
maintainers = [
    { name = "Daniel Foreman-Mackey", email = "foreman.mackey@gmail.com" },
]
requires-python = ">=3.9"
dependencies = ["numpy"]
dynamic = ["version"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://emcee.readthedocs.io"
Source = "https://github.com/dfm/emcee"

[project.optional-dependencies]
extras = ["h5py", "scipy", "tqdm", "ipywidgets"]
tests = ["pytest", "pytest-cov", "coverage[toml]"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/emcee/emcee_version.py"
version_file_template = "__version__ = \"{version}\"\n"

[tool.black]
line-length = 79
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_third_party = ["h5py", "matplotlib", "numpy", "pkg_resources", "pytest", "setuptools"]

[tool.coverage.run]
parallel = true
branch = true
source = ["emcee"]
omit = [
    "emcee/interruptible_pool.py",
    "emcee/mpi_pool.py",
    "emcee/ptsampler.py",
    "docs/*",
    "tests/*",
    "*__init__*"
]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "raise ImportError",
    "except ImportError",
    "def __len__",
    "def __repr__",
    "logging.warning",
    "deprecation_warning",
    "deprecated",
    "if tqdm is None"
]
